# serverless.yml

service: yandex-alice-authentication

# custom:
#   customDomain:
#     domainName: aliceoauth.fletcherist.com
#     stage: dev
#     # basePath: api
#     # certificateName: *.fletcherist.com
#     createRoute53Record: true
#     endpointType: 'regional'

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: eu-central-1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-offline